name: ai2es
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - cudatoolkit
  - cudnn
  - cmake
  - nodejs
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - zarr
  - pyarrow
  - dask
  - pandas
  - scikit-learn
  - shapely
  - scikit-image
  - pyyaml
  - pytest
  - distributed
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - sphinx
  - numba
  - cython
  - tensorflow
  - tensorflow-probability
  - keras
  - shap
  - statsmodels
  - seaborn
  - xmovie
  - xskillscore
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab_widgets
  - pip:
      - scikit-explain
      - jupyterlab-git
